---
- name: install | Lookup erigon user
  getent:
    database: passwd
    key: "{{ erigon_user }}"
  register: erigon_user_entry
  failed_when: false

- name: install | Extract current UID (only if user exists)
  set_fact:
    erigon_current_uid: "{{ erigon_user_entry.ansible_facts.getent_passwd[erigon_user][1] | int }}"
  when: not erigon_user_entry.failed

- name: install | Determine if UID update is needed
  set_fact:
    erigon_uid_needs_update: "{{ erigon_current_uid != erigon_uid }}"
  when: not erigon_user_entry.failed

- name: install | Stop enabled erigon services if UID needs update
  service:
    name: "erigon"
    state: stopped
  when:
    - not erigon_user_entry.failed
    - erigon_uid_needs_update
  become: true

- name: install | Set updated optionally to trigger a systemd restart at the end
  set_fact:
    erigon_state_updates: "{{ erigon_state_updates + ['erigon.uid'] }}"
  when:
    - not erigon_user_entry.failed
    - erigon_uid_needs_update

- name: Ensure erigon group exists
  group:
    name: "{{ erigon_group }}"
    gid: "{{ erigon_gid }}"    
    state: present
  become: true

- name: Create erigon user
  user:
    comment:  erigon client user
    name: "{{ erigon_user }}"
    uid: "{{ erigon_uid }}"
    group: "{{ erigon_group }}"
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ erigon_user }}"
    group: "{{ erigon_group }}"
  loop:
    - "{{ erigon_base_dir }}"
    - "{{ erigon_install_dir }}"    
    - "{{ erigon_config_dir }}"
    - "{{ erigon_data_dir }}"
    - "{{ erigon_log_dir }}"
  become: true

- name: Setup logrotate
  template:
    src: "logrotate/erigon"
    dest: "/etc/logrotate.d/erigon"
    owner: root
    group: root
    mode: 0644    
  become: true

- name: Extract erigon source to install directory
  unarchive:
    src: "{{ erigon_download_url }}"
    remote_src: "{{ true }}"
    dest: "{{ erigon_install_dir }}"
    owner: "{{ erigon_user }}"
    group: "{{ erigon_group }}"
    mode: '0775'
  become: true
  register: extract_src

- name: Create a symlink to current
  file:
    src: "{{ erigon_install_dir }}/"
    dest: "{{ erigon_current_dir }}"
    state: link
  register: create_symlink
  become: true

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    erigon_state_updates: "{{ erigon_state_updates + ['erigon.install_dir'] }}"
  when: >
    extract_src is changed or
    create_symlink is changed

# will throw error the first time you install since the service isnt present
- name: Stop erigon systemd service if running
  service:
    name: erigon
    state: stopped
  when: extract_src is changed 
  become: true
  ignore_errors: true

