---
- name: Install erigon
  include_tasks: "install.yml"

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not erigon_host_ip

- name: Create cmd line args
  include_tasks: "cmdline.yml"

- name: Create erigon service
  include_tasks: "service.yml"