---

- name: Fetch architecture of the host
  debug:
    var: ansible_facts.architecture

- name: Set system architecture to download appropriate binary
  set_fact:
    erigon_architecture: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"

- name: Install erigon
  include_tasks: "install.yml"

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not erigon_host_ip

- name: Create cmd line args
  include_tasks: "cmdline.yml"

- name: Create erigon service
  include_tasks: "service.yml"

- name: Set version info on a local file
  include_tasks: "tags.yml"
