---
- name: Get the default ipv4 address
  set_fact:
    erigon_host_ip: >-
      {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] if
      hostvars[inventory_hostname]['ansible_default_ipv4']['address'] is
      defined else '127.0.0.1' }}

- name: Fetch public IP 
  uri:
    url: http://ifconfig.me/ip
    method: GET
    return_content: yes
    status_code: 200
  register: erigon_public_ip_output
  ignore_errors: True

- name: Set the host ip
  set_fact:
    erigon_host_ip: "{{ erigon_public_ip_output.content }}"
  when: erigon_public_ip_output.status == 200
